version: "2"
services:
    client:
        image: webapp-client
        restart: always
        build: ./client
        ports:
            - '3000:3000'
        volumes:
            - ./client:/client
            - /client/node_modules
        entrypoint: ["npm", "start"]
        depends_on:
            - api
        networks:
            - webappnetwork
        stdin_open: true
    api:
        image: webapp-api
        restart: always
        build: ./api
        ports:
            - '9000:9000'
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
        stdin_open: true
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        ports:
            - '27017:27017'
        command: mongod --noauth
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge